plot_parameters = {
    "axes.labelsize": 24,
    "axes.linewidth": 2,
    "figure.dpi": 300,
    "figure.figsize": (8.0, 8.0),
    "font.family": "serif",
    "font.sans-serif": "Computer Modern Sans Serif",
    "font.size": 24,
    "legend.fontsize": 16,
    "legend.loc": "lower center",
    "legend.fancybox": False,
    "lines.linewidth": 3,
    "lines.markersize": 16,
    "lines.markeredgewidth": 3,
    "markers.fillstyle": "none",
    "mathtext.fontset": "cm",
    "xtick.direction": "in",
    "xtick.labelsize": 24,
    "xtick.major.width": 1.6,
    "xtick.top": True,
    "ytick.direction": "in",
    "ytick.labelsize": 24,
    "ytick.major.width": 1.6,
    "ytick.right": True,
}
